//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessEntityPhone
    {
        public int BusinessEntityPhoneID { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> PhoneNumberTypeID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
