using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.VisualStudio.TestTools.UnitTesting;

// ReSharper disable once CheckNamespace
namespace NorthWindCoreUnitTest
{
    public partial class ProductsTest
    {
        private readonly string ProductFile = "Products.txt";
        private readonly string ProductOrderByCategoryFile = "ProductOrderedByCategory.txt";
        
        /// <summary>
        /// Perform any initialize for the class
        /// </summary>
        /// <param name="testContext"></param>
        [ClassInitialize()]
        public static void ClassInitialize(TestContext testContext)
        {
            TestResults = new List<TestContext>();
        }

        /// <summary>
        /// Code to run prior to specific test methods
        /// </summary>
        [TestInitialize]
        public void Initialization()
        {
            DeleteProductFiles();
        }

        /// <summary>
        /// Delete text files generated by the following test methods
        /// </summary>
        private void DeleteProductFiles()
        {
            if (TestContext.TestName == nameof(GroupProductByCategoryThenByProductOrderByCategoryNameTask))
            {
                if (File.Exists(ProductFile))
                {
                    File.Delete(ProductFile);
                }
            }

            if (TestContext.TestName == nameof(OrderedByCategoryNameTask))
            {
                if (File.Exists(ProductOrderByCategoryFile))
                {
                    File.Delete(ProductOrderByCategoryFile);
                }
            }
        }
    }
}
